name=DPV
version=1.0.0
author=Javier <tolejavy@gmail.com>
maintainer=Javier 
sentence=Calcula el Déficit de Presión de Vapor (DPV/VPD) en Arduino.
paragraph=Implementa la fórmula de Magnus-Tetens para estimar la presión de vapor saturante y calcular el DPV a partir de temperatura y humedad relativa. Ideal para agricultura, invernaderos, meteorología y control ambiental.
category=Sensors
url=
architectures=*
repository=
license=
includes=DPV.h