name=DPV
version=1.0.0
author=Javier Ernesto <tolejavy@gmail.com>
maintainer=Javier Ernesto <tolejavy@gmail.com>
sentence=Calcula el Déficit de Presión de Vapor (DPV/VPD) en Arduino (FAO-56).
paragraph=Implementación estática de la fórmula FAO-56 (Magnus-Tetens) para estimar la presión de vapor saturante y el DPV a partir de temperatura y humedad relativa. Pensada para agricultura de precisión, invernaderos, meteorología y control ambiental.
category=Sensors
url=https://github.com/javierernesto/DPV
architectures=*
repository=git+https://github.com/javierernesto/DPV.git
license=MIT
includes=DPV.h
